export const allDataUsers = [
  {
    id: 1,
    role: "Admin1",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: true,
  },
  {
    id: 2,
    role: "Admin2",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: false,
  },
  {
    id: 3,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: true,
  },
  {
    id: 4,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: false,
  },
  {
    id: 5,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: true,
  },
  {
    id: 6,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: false,
  },
  {
    id: 7,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: true,
  },
  {
    id: 8,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: true,
  },
  {
    id: 9,
    role: "Admin",
    lastName: "Suyunov",
    firstName: "Elbek",
    email: "elbekjon@gmail.com",
    active: false,
  },
];
